dist:
  module: github.com/prometheus/prometheus-opentelemetry-collector/cmd/prometheusotelcol
  name: prometheus-otelcol
  description: Prometheus-flavored OpenTelemetry Collector distribution.
  output_path: ./_build
  version: 0.1.0-dev

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.151.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver v0.154.0
  - gomod: github.com/prometheus/prometheus-opentelemetry-collector/receivers/stackdriver v0.0.0
  - gomod: github.com/prometheus/prometheus-opentelemetry-collector/receivers/yace v0.0.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.151.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.151.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.151.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.151.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.151.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.154.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.151.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.57.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.57.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.57.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.57.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.57.0

telemetry:
  gomod: go.opentelemetry.io/collector/service v0.151.0
  import: go.opentelemetry.io/collector/service/telemetry/otelconftelemetry

replaces:
  - github.com/prometheus/prometheus-opentelemetry-collector/receivers/stackdriver => ../receivers/stackdriver
  - github.com/prometheus/prometheus-opentelemetry-collector/receivers/yace => ../receivers/yace
