// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/mysqld_exporter component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("mysqld_exporter")
	ScopeName = "github.com/prometheus/prometheus-opentelemetry-collector/receivers/mysqld"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
