// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverPostgresExporterOTelSemanticConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.postgresExporter.OTelSemanticConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("Enables OpenTelemetry semantic convention transformations for postgres_exporter metrics."),
	featuregate.WithRegisterReferenceURL("https://github.com/prometheus/prometheus-opentelemetry-collector/pull/21"),
	featuregate.WithRegisterFromVersion("v0.1.0"),
)
